name: Auto Create Pull Request from Feature Branch to Main
on:
  push:
    branches:
      - feature_branch
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      id: create-pr
      run: |
        gh pr create --title "Auto-created PR" \
                     --body "This PR is automatically created." \
                     --base main \
                     --head feature_branch \
                     --label "automated"
      
    - name: Add reviewer to PR
      run: |
        PR_NUMBER=$(gh pr list --state open --head feature_branch --json number -q '.[0].number')
        gh pr review $PR_NUMBER --request-reviewer venkatalakshmi1430
