name: Auto Merge Pull Request After Approval
on:
  pull_request:
    types:
      - review_requested
      - approved
jobs:
  merge-pr:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.mergeable_state == 'clean'  # Ensure the PR is open and mergeable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/github.asc
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Get PR number
      id: get_pr_number
      run: |
        PR_NUMBER=$(gh pr list --state open --head feature_branch --json number -q '.[0].number')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV  # Export the PR number as an environment variable

    - name: Merge Pull Request
      run: |
        gh pr merge ${{ env.PR_NUMBER }} --merge --delete-branch
