name: Auto Create Pull Request from Feature Branch to Main
on:
  push:
    branches:
      - feature_branch
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2

    - name: Authenticate with GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"  # Correct way to authenticate with the GitHub token

    - name: Create Pull Request
      run: |
        gh pr create --base main --head feature_branch --title "Feature PR" --body "This PR implements a new feature."

    - name: Assign Reviewer(s) to the PR
      run: |
        PR_NUMBER=$(gh pr list --state open --head feature_branch --json number -q '.[0].number')  # Get the PR number for the feature branch
        gh pr review $PR_NUMBER --request-reviewer venkatalakshmi1430
