name: Auto Merge Pull Request After Approval
on:
  pull_request:
    types:
      - review_requested
      - approved
jobs:
  merge-pr:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.mergeable_state == 'clean'  # Ensure the PR is open and mergeable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/github.asc
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Merge Pull Request
      uses: devops-infra/action-pull-request-merge@v0.2.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_number: ${{ github.event.pull_request.number }}  # PR number
