name: Call docker image build and push reusable workflow
on:
  push:
    branches:
      - feature_branch
jobs:
  call-docker-build-push:
    uses: ./.github/workflows/PR_check_script.yml
    with:
      dockerfile: './Dockerfile'
      dockerhub_repo: 'venkatalakshmi0448/nodejs-docker'
      deploy_env: 'production'

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
