name: Build and Push Docker Image
on:
  push:
    branches:
      - feature_branch
  pull_request:
    types:
      - closed  # Trigger the workflow when the PR is closed (merged or manually closed)
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to the Dockerfile'
        required: true
        type: string
        default: './Dockerfile'
      dockerhub_repo:
        description: 'Dockerhub repo name'
        required: true
        type: string
        default: 'venkatalakshmi0448/nodejs-docker'
      deploy_env:
        description: 'Deployment environment'
        required: true
        type: string
        default: 'staging'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'  # Ensure the job runs for both PR merged and push event

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v3
      with: 
         images: venkatalakshmi0448/nodejs-docker

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.dockerfile }} 
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      needs: build-and-push  # Ensures this step runs only after the build-and-push job
      steps:
       - run: |
              echo "The PR was merged. Proceeding with further steps."
